USE [18017_DB]
GO

/****** Object:  Index [tip_kor_unq]    Script Date: 3.7.2018. 18:11:06 ******/
ALTER TABLE [dbo].[tip_korisnika] ADD  CONSTRAINT [tip_kor_unq] UNIQUE NONCLUSTERED 
(
	[naziv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

