//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalika.Podatkovni_sloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class izdatnica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public izdatnica()
        {
            this.stanje_skladista = new HashSet<stanje_skladista>();
            this.stavke_izdatnice = new HashSet<stavke_izdatnice>();
        }
    
        public int ID_izdatnica { get; set; }
        public System.DateTime datum_izdatnice { get; set; }
        public string napomena { get; set; }
        public int ID_zaposlenik { get; set; }
        public int ID_nalog { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        public virtual radni_nalog radni_nalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stanje_skladista> stanje_skladista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavke_izdatnice> stavke_izdatnice { get; set; }
    }
}
