//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalika.Podatkovni_sloj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<izdatnica> izdatnica { get; set; }
        public virtual DbSet<jedinica_mjere> jedinica_mjere { get; set; }
        public virtual DbSet<korisnik> korisnik { get; set; }
        public virtual DbSet<materijal> materijal { get; set; }
        public virtual DbSet<poslovni_partner> poslovni_partner { get; set; }
        public virtual DbSet<primka> primka { get; set; }
        public virtual DbSet<proizvod> proizvod { get; set; }
        public virtual DbSet<projekt> projekt { get; set; }
        public virtual DbSet<radni_nalog> radni_nalog { get; set; }
        public virtual DbSet<stanje_skladista> stanje_skladista { get; set; }
        public virtual DbSet<stavke_izdatnice> stavke_izdatnice { get; set; }
        public virtual DbSet<stavke_naloga> stavke_naloga { get; set; }
        public virtual DbSet<stavke_primke> stavke_primke { get; set; }
        public virtual DbSet<tip_korisnika> tip_korisnika { get; set; }
        public virtual DbSet<stanje_skladista_pogled> stanje_skladista_pogled { get; set; }
    }
}
