//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalika.Podatkovni_sloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class primka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public primka()
        {
            this.stanje_skladista = new HashSet<stanje_skladista>();
            this.stavke_primke = new HashSet<stavke_primke>();
        }
    
        public int ID_primka { get; set; }
        public System.DateTime datum_primke { get; set; }
        public string napomena { get; set; }
        public int ID_dobavljac { get; set; }
        public int ID_zaposlenik { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        public virtual poslovni_partner poslovni_partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stanje_skladista> stanje_skladista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavke_primke> stavke_primke { get; set; }
    }
}
