//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalika.Podatkovni_sloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class projekt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public projekt()
        {
            this.proizvod = new HashSet<proizvod>();
            this.radni_nalog = new HashSet<radni_nalog>();
        }
    
        public int ID_projekt { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public string odobren { get; set; }
        public Nullable<System.DateTime> datum_odobrenja { get; set; }
        public int ID_zaposlenik { get; set; }
        public int ID_klijent { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        public virtual poslovni_partner poslovni_partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proizvod> proizvod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<radni_nalog> radni_nalog { get; set; }
    }
}
