//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalika.Podatkovni_sloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class radni_nalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public radni_nalog()
        {
            this.izdatnica = new HashSet<izdatnica>();
            this.stavke_naloga = new HashSet<stavke_naloga>();
        }
    
        public int ID_nalog { get; set; }
        public string opis_postupka { get; set; }
        public System.DateTime datum_pocetka { get; set; }
        public System.DateTime datum_zavrsetka { get; set; }
        public int ID_zaposlenik { get; set; }
        public int ID_projekt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izdatnica> izdatnica { get; set; }
        public virtual korisnik korisnik { get; set; }
        public virtual projekt projekt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavke_naloga> stavke_naloga { get; set; }
    }
}
