//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalika.Podatkovni_sloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class stanje_skladista_pogled
    {
        public string naziv_materijala { get; set; }
        public Nullable<int> trenutno_stanje { get; set; }
        public int ID_materijal { get; set; }
    }
}
