//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalika.Podatkovni_sloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class stavke_primke
    {
        public int ID_stavka_primke { get; set; }
        public int ID_primka { get; set; }
        public int ID_materijal { get; set; }
        public int kolicina { get; set; }
        public double cijena { get; set; }
    
        public virtual materijal materijal { get; set; }
        public virtual primka primka { get; set; }
    }
}
